[build]
  command = "npm run build"

[build.environment]
  DATABASE_URL = "postgresql://neondb_owner:npg_6MvLFxYIn8Ck@ep-dawn-base-agemj0hc-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  NEXTAUTH_URL = "https://zcorp.netlify.app"
  NEXTAUTH_SECRET = "zcorp-secret-key-change-me-in-production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
